'use client';
import {useState} from 'react';
import Workspace from './Workspace';
import LiveOpportunities from './LiveOpportunities';
import {LayoutDashboard,Radar,Map,CalendarClock,Handshake,Megaphone,KanbanSquare,BarChart3,Search,Bell,Building2,HardHat,Users,CircleDollarSign,ChevronRight,ShieldCheck,CheckCircle2,Phone,Mail} from 'lucide-react';
const nav=[['Command Center',LayoutDashboard],['Opportunities',Radar],['Market Intelligence',Search],['Territory',Map],['Renewal Radar',CalendarClock],['Referral Network',Handshake],['Campaigns',Megaphone],['Pipeline',KanbanSquare],['Analytics',BarChart3]];
const demo=[{score:94,name:'Coastal Construction Group',meta:'General Contractor · Fort Myers · 34 employees',x:'112 days'},{score:91,name:'Gulfshore Marine Services',meta:'Marine Contractor · Naples · 27 employees',x:'86 days'},{score:88,name:'Island Hospitality Group',meta:'Hospitality · Marco Island · 52 employees',x:'73 days'}];
const changes=[['9:42 AM','Gulfshore Builders','New commercial permit detected','HIGH'],['8:17 AM','Naples Property Group','$3.7M commercial property transaction','HIGH'],['Yesterday','Coastal Marine Services','Hiring activity increased 18 → 27','MED'],['Yesterday','Harbor Grill LLC','New business / liquor-license activity','MED']];
const signals=[{name:'Coastal Construction Group',detail:'Commercial property acquisition + active permits',score:94,icon:Building2},{name:'Gulfshore Marine Services',detail:'Hiring acceleration + new operating location',score:91,icon:Users},{name:'Gulfshore Builders',detail:'New commercial permit filed this morning',score:84,icon:HardHat},{name:'Harbor Grill LLC',detail:'New entity + liquor-license activity',score:81,icon:CircleDollarSign}];
function MarketIntelligence(){const [sel,setSel]=useState(0),[toast,setToast]=useState('');const s=signals[sel];const act=m=>{setToast(m);setTimeout(()=>setToast(''),1800)};return <div className="demo"><div className="demoHero"><div><div className="eyebrow">REPRESENTATIVE SIGNAL DATA</div><h2>Market Intelligence Engine</h2><p>This module remains in validation mode while free public-data sources are connected. Opportunities is now live.</p></div><div className="demoStats"><div className="demoStat"><b>187</b><span>Demo signals</span></div><div className="demoStat"><b>31</b><span>Demo weekly</span></div></div></div><div className="demoGrid"><section className="demoPanel"><h3>Detected Opportunities</h3><p>Representative records for workflow validation.</p><div className="signalCards">{signals.map((x,i)=>{const I=x.icon;return <div key={x.name} className={'signalCard '+(sel===i?'selected':'')} onClick={()=>setSel(i)}><div className="signalIcon"><I/></div><div><b>{x.name}</b><span>{x.detail}</span></div><span className="signalScore">{x.score}</span></div>})}</div></section><section className="demoPanel"><h3>Risk & Growth Intelligence</h3><p>Why this business would surface.</p><div className="intelBox"><small>DEMO SCORE {s.score}/100</small><h4>{s.name}</h4><p>{s.detail}. Multiple signals can indicate a timely commercial insurance conversation.</p></div><div className="demoButtons"><button onClick={()=>act('Use Opportunities → New Opportunity for persistent records')}>OPEN LIVE WORKFLOW</button></div></section></div>{toast&&<div className="toastDemo"><b>Validation mode</b><span>{toast}</span></div>}</div>}
function Command(){return <><div className="kpis"><K label="Qualified Pipeline" val="$4.26M" sub="Representative"/><K label="New Opportunities" val="31" sub="Representative"/><K label="High Intent" val="12" sub="Representative" hot/><K label="Upcoming X-Dates" val="18" sub="Representative"/><K label="Referral Leads" val="7" sub="Representative"/></div><div className="gridTop"><section className="panel radar"><Title t="Opportunity Radar" s="Representative intelligence until live feeds are connected" badge="DEMO"/><div className="topOpp"><div className="score"><strong>94</strong><span>DEMO<br/>SCORE</span></div><div className="oppBody"><div className="rank">EXAMPLE OPPORTUNITY</div><h2>Coastal Construction Group</h2><p>General Contractor · Fort Myers · 34 employees</p><div className="chips"><span>New property</span><span>3 active permits</span><span>Fleet expanding</span></div></div></div><div className="miniOpps">{demo.slice(1).map(o=><div className="mini" key={o.name}><strong>{o.score}</strong><div><b>{o.name}</b><span>{o.meta}</span></div><span className="xd">X-Date ≈ {o.x}</span><ChevronRight size={17}/></div>)}</div></section><section className="panel changed"><Title t="What Changed" s="Representative market signals" badge="DEMO"/>{changes.map((c,i)=><div className="change" key={c[1]}><div className={'eventIcon e'+i}>{i===0?<HardHat/>:i===1?<Building2/>:i===2?<Users/>:<CircleDollarSign/>}</div><div><span className="time">{c[0]}</span><b>{c[1]}</b><p>{c[2]}</p></div><span className={'priority '+c[3].toLowerCase()}>{c[3]}</span></div>)}</section></div></>}
export default function Home(){const [active,setActive]=useState('Command Center');const view=active==='Command Center'?<Command/>:active==='Opportunities'?<LiveOpportunities/>:active==='Market Intelligence'?<MarketIntelligence/>:<Workspace name={active}/>;return <main className="shell"><aside><div className="brand"><div className="mark">U</div><div><b>UTECHT</b><span>INSURANCE UNDERWRITERS</span></div></div><div className="sectionLabel">GROWTH INTELLIGENCE</div><nav>{nav.map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>setActive(n)}><I size={18}/><span>{n}</span></button>)}</nav><div className="sideFoot"><ShieldCheck size={18}/><div><b>Commercial P&C</b><span>Growth Intelligence</span></div></div></aside><section className="content"><header><div><div className="eyebrow">COMMERCIAL P&C · SOUTHWEST FLORIDA</div><h1>{active}</h1><p>{active==='Opportunities'?'Live authenticated database workspace':'Validation workspace · representative data where labeled'}</p></div><div className="headerActions"><div className="search"><Search size={17}/><span>Search businesses, contacts...</span></div><button className="icon"><Bell size={18}/><i/></button><div className="avatar">DC</div></div></header>{view}</section></main>}
function K({label,val,sub,hot}){return <div className={'kpi '+(hot?'hot':'')}><span>{label}</span><strong>{val}</strong><small>{sub}</small></div>};function Title({t,s,badge}){return <div className="title"><div><h3>{t}</h3><p>{s}</p></div>{badge&&<span className="live"><i/>{badge}</span>}</div>}
